# Generated by Django 3.2.6 on 2021-11-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20211111_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist_items',
            new_name='product',
        ),
    ]
