# Generated by Django 3.2.6 on 2021-11-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_deliveryaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='default_country',
            new_name='delivery_country',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='default_phone_number',
            new_name='delivery_postcode',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='default_street_address1',
            new_name='delivery_street_address1',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='default_street_address2',
            new_name='delivery_street_address2',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='default_town_or_city',
            new_name='delivery_town_or_city',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='default_postcode',
        ),
    ]
