# Generated by Django 3.2.6 on 2021-11-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_deliveryaddress_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
