# Generated by Django 3.2.6 on 2021-10-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='county',
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='Name', max_length=50),
            preserve_default=False,
        ),
    ]
