# Generated by Django 3.2.6 on 2021-11-21 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_delete_deliveryaddress'),
        ('products', '0004_alter_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='username',
        ),
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.userprofile'),
        ),
    ]
